export enum Config {
  START_SCORE = 0,
  START_LEVEL = 1,
  START_SPEED = 1000,
  SCORE_STEP = 100,
  SPEED_STEP = 25,
  LEVEL_STEP = 1,
  SCORE_LEVEL_INCREASE = 500,
  MAIN_FIELD_ROWS = 20,
  MAIN_FIELD_COLUMNS = 10,
  EXTRA_FIELD_ROWS = 6,
  EXTRA_FIELD_COLUMNS = 6,
  CELLS_SELECTOR_MAIN = '#main_field div',
  CELLS_SELECTOR_EXTRA = '#extra_field div',
  CONTAINER_SELECTOR = '#container',
  START_DIALOG_SELECTOR = '#start_dialog',
  GAME_OVER_DIALOG_SELECTOR = '#game_over_dialog',
  MAIN_FIELD_SELECTOR = '#main_field',
  EXTRA_FIELD_SELECTOR = '#extra_field',
  SCORE_SELECTOR = '#score',
  LEVEL_SELECTOR = '#level',
  LINES_SELECTOR = '#lines',
  PAUSE_SELECTOR = '#pause',
}