export enum Config {
  START_SCORE = 0,
  START_LEVEL = 1,
  START_SPEED = 1000,
  SCORE_STEP = 100,
  SPEED_STEP = 25,
  LEVEL_STEP = 1,
  SCORE_LEVEL_INCREASE = 500,
  MAIN_FIELD_ROWS = 20,
  MAIN_FIELD_COLUMNS = 10,
  EXTRA_FIELD_ROWS = 6,
  EXTRA_FIELD_COLUMNS = 6,
  CELLS_MAIN = '#main_field div',
  CELLS_EXTRA = '#extra_field div',
  CONTAINER = '#container',
  START_DIALOG = '#start_dialog',
  GAME_OVER_DIALOG = '#game_over_dialog',
  MAIN_FIELD = '#main_field',
  EXTRA_FIELD = '#extra_field',
  SCORE = '#score',
  LEVEL = '#level',
  LINES = '#lines',
  PAUSE = '#pause',
}